sudo cat /opt/radiologger/.env | grep DATABASE_URL
 root@vpn:~# sudo cat /opt/radiologger/.env | grep DATABASE_URL                  
 DATABASE_URL=postgresql://radiologger:U.Mot.W#rden.Opg5Numen.#21dag@localhost:54
 32/radiologger                                                                  
 
de door mij ingestelde password staat in de url daar is dus denk ik iets fout gegaan?

 root@vpn:~# sudo -u postgres psql -c "\du"                                      
                               List of roles                                     
   Role name  |                         Attributes                               
 -------------+------------------------------------------------------------      
  postgres    | Superuser, Create role, Create DB, Replication, Bypass RLS       
  radiologger |                                                                  
                                                                                 
 

dit lijkt allemaal wel te kloppen.

Gunicorn  handmatige restart geeft ondermeer dit

     return self.load_wsgiapp()                                                  
            ^^^^^^^^^^^^^^^^^^^                                                  
   File "/opt/radiologger/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.
 py", line 47, in load_wsgiapp                                                   
     return util.import_app(self.app_uri)                                        
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                        
   File "/opt/radiologger/venv/lib/python3.12/site-packages/gunicorn/util.py", li
 ne 370, in import_app                                                           
     mod = importlib.import_module(module)                                       
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                       
   File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module   
     return _bootstrap._gcd_import(name[level:], package, level)                 
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 
   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import               
   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load            
   File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked   
 ModuleNotFoundError: No module named 'main'                                     
 [2025-03-30 17:20:51 +0000] [29746] [INFO] Worker exiting (pid: 29746)          
 [2025-03-30 17:20:51 +0000] [29745] [DEBUG] 1 workers                           
 [2025-03-30 17:20:51 +0000] [29745] [ERROR] Worker (pid:29746) exited with code 
 3                                                                               
 [2025-03-30 17:20:51 +0000] [29745] [ERROR] Shutting down: Master               
 [2025-03-30 17:20:51 +0000] [29745] [ERROR] Reason: Worker failed to boot.      
 