Ik heb de boel opnieuw geinstalleerd maar bij de 502 error krijgen hier wat de logs zoal melden:
 root@vpn:~# tail -n 20 /var/log/nginx/radiologger_error.log                     
 2025/03/30 16:29:23 [error] 25819#25819: *7 connect() failed (111: Connection re
 fused) while connecting to upstream, client: 154.28.229.209, server: logger.pilo
 tradio.nl, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: 
 "logger.pilotradio.nl"                                                          
 2025/03/30 16:29:23 [error] 25819#25819: *6 connect() failed (111: Connection re
 fused) while connecting to upstream, client: 154.28.229.107, server: logger.pilo
 tradio.nl, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: 
 "logger.pilotradio.nl"                                                          
 2025/03/30 16:29:31 [error] 25819#25819: *10 recv() failed (104: Connection rese
 t by peer) while reading response header from upstream, client: 154.28.229.253, 
 server: logger.pilotradio.nl, request: "GET / HTTP/1.1", upstream: "http://127.0
 .0.1:5000/", host: "logger.pilotradio.nl"                                       
 2025/03/30 16:32:41 [error] 25819#25819: *71 connect() failed (111: Connection r
 efused) while connecting to upstream, client: 92.110.129.49, server: logger.pilo
 tradio.nl, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: 
 "logger.pilotradio.nl"                                                          
 

deel uit de radiologger logfile:
                     ^^^^^^^^^^^                                                 
   File "/opt/radiologger/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.
 py", line 57, in load                                                           
     return self.load_wsgiapp()                                                  
            ^^^^^^^^^^^^^^^^^^^                                                  
   File "/opt/radiologger/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.
 py", line 47, in load_wsgiapp                                                   
     return util.import_app(self.app_uri)                                        
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                        
   File "/opt/radiologger/venv/lib/python3.12/site-packages/gunicorn/util.py", li
 ne 370, in import_app                                                           
     mod = importlib.import_module(module)                                       
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                       
   File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module   
     return _bootstrap._gcd_import(name[level:], package, level)                 
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 
   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import               
   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load            
   File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked   
 ModuleNotFoundError: No module named 'main'                                     
 [2025-03-30 16:45:21 +0000] [26702] [INFO] Worker exiting (pid: 26702)          
 [2025-03-30 16:45:21 +0000] [26700] [ERROR] Worker (pid:26702) exited with code 
 3                                                                               
 
